# Generated by Django 6.0.2 on 2026-02-26 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('slot', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('registered_time', models.DateField()),
                ('isValid', models.BooleanField(default=True)),
            ],
        ),
    ]
